apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-baseline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DeeSanas/hybrid-cloud-reference-architecture.git
    targetRevision: main
    path: projects/gitops-argocd-platform/bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
